name: check

on:
  push:
    branches: main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 0

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - uses: dtolnay/rust-toolchain@1.87.0
        with:
          components: rustfmt, clippy
      
      - name: Cargo cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          path: ~/.cargo/registry

      - name: build
        run: cargo build

      - name: check moonc version (Unix)
        if: runner.os != 'Windows'
        run: ./target/debug/moonc_wasm -v

      - name: check moonc version (Windows)
        if: runner.os == 'Windows'
        run: .\target\debug\moonc_wasm.exe -v
